# Check Pull Requests
# See also: .github/workflows/scripts

name: PR Check

on:
  pull_request:
    branches:
      - master
    types: [opened] # todo: synchronize

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate checklists
        uses: roryq/checkmate@master
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-:

      - name: Setup Requirements
        run: |
          pip install -r scripts/requirements.txt

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          json: true
          write_output_files: true

      - name: Check and report
        run: |
          python .github/workflows/scripts/check.py
        env:
          github_api_token: ${{ secrets.GITHUB_TOKEN }} # scripts
          PR_NUMBER: ${{ github.event.number }} # gh_cli
