name: Catalogue CI

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      squash_history:
        description: Select if you want the history to be squashed
        type: boolean
        default: false

jobs:
  update:
    uses: ./.github/workflows/_update.yml
    secrets: inherit
    with:
      check: true
      squash_history: ${{ inputs.squash_history || false }}
