name: Plugin Check

on:
  pull_request:
    branches:
      - master
    paths:
      - 'plugins/**'
    types: [opened, synchronize]

jobs:
  plugin-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-:

      - name: Setup Requirements
        run: |
          pip install -r scripts/requirements.txt

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: | 
            plugins/*/*.json
          json: true
          write_output_files: true

      - name: Check plugins
        run: |
          python .github/workflows/scripts/pr_check.py
        env:
          github_api_token: ${{ secrets.GITHUB_TOKEN }}
