name: Plugin Check

on:
  pull_request:
    branches:
      - master
    paths:
      - 'plugins/**'
    types: [opened, synchronize]

jobs:
  plugin-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-:

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: | 
            **/*.json
          json: true
          write_output_files: true
      
      - name: Check output
        run: | 
          cat .github/outputs/all_changed_and_modified_files.json

      - name: Check plugins
        run: |
          cd ./scripts
          pip install -r requirements.txt
          python pr_check.py
        env:
          github_api_token: ${{ secrets.TOKEN_FOR_GITHUB_API }}
