name: PR Check

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-:

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.6

      - name: Check plugins
        run: |
          cd ./scripts
          pip install -r requirements.txt
          plugins=""
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file =~ ^plugins\/([a-z0-9_]*) ]]; then
              plugins="${plugins}${BASH_REMATCH[1]},"
            fi
          if [[ $plugins == "" ]]; then
            echo Hmm, no plugin changes found. Let\'s skip this part.
          else
            plugins=${plugins%,}
            echo Well, seems there's plugin(s) added or modified. let's run a check for: $plugins
            python main.py check --id $plugins
          fi
          done
          
        env:
          github_api_token: ${{ secrets.TOKEN_FOR_GITHUB_API }}
