on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

name: Checklist
jobs:
  validate-checklists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate Checklists
        uses: roryq/checkmate@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          preamble: |
            ## 合并前检查单
            感谢您的贡献。请等待插件仓库维护者检查您的插件。
          paths: |
            plugins/**:
              - 插件名称符合其功能、没有歧义
              - 仓库属于提交者本人或本人为仓库维护者
              - 分类正确
              - 应当有可阅读插件说明，且内容足以帮助用户使用
              - 若使用了插件仓库文件作为介绍，文件应当有效，检查时应当注意相对路径
              - 其他应当检查并予以合并或不合并的情况
