name: Scheduled update

on:
  schedule:
    # Runs at minute 15 and 45 of every hour
    - cron: '15,45 * * * *'

jobs:
  update:
    uses: ./.github/workflows/_update.yml
    secrets: inherit
    with:
      check: false
      squash_history: false
